In [6]:
import functools
import pandas as pd
import numpy as np
import tqdm
import seaborn as sns
import xarray as xr
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import scipy.integrate as scint
import scipy.interpolate as scinterp
xr.set_options(keep_attrs=True)
import cmath

from Functions import *

In [12]:
#WA_Scan = np.load("Savetest_WA.npy")
NA_Scan = np.load("SaveTest_NA.npy")

In [22]:
print(NA_Scan)

[[[1.43853801e+29 0.00000000e+00]
  [2.52003188e+35 0.00000000e+00]
  [1.84387888e+36 0.00000000e+00]
  [1.65530862e+36 0.00000000e+00]
  [1.15984643e+36 0.00000000e+00]]

 [[2.50537991e+29 0.00000000e+00]
  [1.14475078e+36 0.00000000e+00]
  [2.82829991e+36 0.00000000e+00]
  [1.99324291e+36 0.00000000e+00]
  [1.26008301e+36 0.00000000e+00]]

 [[3.76291087e+29 0.00000000e+00]
  [3.44646530e+36 0.00000000e+00]
  [3.83706380e+36 0.00000000e+00]
  [2.24378216e+36 0.00000000e+00]
  [1.30004551e+36 0.00000000e+00]]

 [[5.23116514e+29 0.00000000e+00]
  [6.64089077e+36 0.00000000e+00]
  [4.71168116e+36 0.00000000e+00]
  [2.37479768e+36 0.00000000e+00]
  [1.27371929e+36 0.00000000e+00]]

 [[7.11124806e+29 0.00000000e+00]
  [9.51359041e+36 0.00000000e+00]
  [5.27824573e+36 0.00000000e+00]
  [2.36709631e+36 0.00000000e+00]
  [1.18519547e+36 0.00000000e+00]]]
